#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X

#xrandr --output DP-4 --primary --mode 1920x1080 --rate 119.93 --pos 0x0
#xrandr --output HDMI-0 --mode 1920x1080 --rate 60 --pos 1920x0
xinput --set-prop 15 'Coordinate Transformation Matrix' 0.6 0 0 0 0.6 0 0 0 1
#xrandr --output HDMI-0 --mode 1920x1080 --rate 60 --pos 1920x0 --rotate right

bspc monitor DP-4 -d 1 2 3 4 5 6 7 8
bspc monitor HDMI-0 -d 9 S

bspc config normal_border_color "#666666"
bspc config focused_border_color "#B2B2B2"

bspc config focus_follows_pointer true

sxhkd &
$HOME/.config/polybar/launch.sh &

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a thunar state=floating
#bspc rule -a NomeDaClasse:slack do=S
bspc rule -a Slack desktop='HDMI-0:^9' follow=on

bspc rule -a google-chrome-stable desktop='DP-4:^1' follow=on

setxkbmap us intl &
picom -fb &
slack &
google-chrome-stable &
xsetroot -cursor_name left_ptr
nitrogen --restore
xset s off
xset -dpms
xrandr --output DP-4 --mode 1920x1080 --rate 120 --primary --output HDMI-0 --mode 1920x1080 --rotate right --right-of DP-4
feh --bg-fill ~/.config/backgrounds/1156762.png  --bg-fill ~/.config/backgrounds/1156762.png 
